// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package testdata generated by go-bindata.// sources:
// testdata/router/ca-bundle.pem
// testdata/router/coreDNS-pod.yaml
// testdata/router/egressfirewall-multiDomain.yaml
// testdata/router/egressfirewall-wildcard.yaml
// testdata/router/test-client-pod.yaml
// testdata/router/testpod-60350.yaml
// testdata/router/testpod-60492.yaml
// testdata/router/web-server-v4v6rc.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _routerCaBundlePem = []byte(`-----BEGIN CERTIFICATE-----
MIIFDTCCAvWgAwIBAgIUDtkk2PPE+b/uQ8STNJNyuacqLq8wDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKTkUtVGVzdC1DQTAgFw0yNTAxMTcwMzA0NDJaGA8yMDc1
MDExNzAzMDQ0MlowFTETMBEGA1UEAwwKTkUtVGVzdC1DQTCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAJMUI8/l6x4IDw0uQtJo0f9kV3ogWkgi4yU6UD4c
Wln8TMyg4kwLDg/sADd9o7dGnReLpc0ojnZpsJwBe7AyqmYTv7Q7IfWBmo1Cic5G
FdUbFS77YcIdyU77e7S1iWIt642wJShodU6i6suqvbraR9rNv7YuDs37GRsECHlj
IDRP2GStQqVtyPWLZ8+yG+3COIq+eUD9atsqmGrAYCe4IVy1lDi37g7nupveIFTM
FqQP4NFhTKCEW0ZhnaTHukOOOKRsnec5KV1rbdtkFBH035ECrkIbUemPwuZv+hMH
WNq4cfE8osT6RsY0rxKdGrteUAb7LZJZ3EiK+f7agekO9rvtekq63tMPsbJz4JOj
vNeF0oifvrQYeL4Lv4OGxjI37pwCmbc/f95Dg9P6I9on9/h/Yyyejhlkd7nFNjDL
RhtikKR/at20QF2QKvAb+1CTexa9xIhzMY9ZxtCvQ/PJM5PRHxYv+kSDhfJqFoHc
be6SP2oXZEiXhVlWKCTnuUHjSa6sBgJlZDoT0k5mORWn64WQqBG+L+ywzvbqZX0J
08+mHvpDRQwzOOJg+3IQhsMQDaQ6w7nE9CEHv9Oh1mgoGDSPDr1NIYPRdZ5os1h5
w4sGjnxAzCTX36xU3XqkGLuDsOiBxkf+skIqZ88fr331KvQSbBw2Ia662q2SddDy
ArO3AgMBAAGjUzBRMB0GA1UdDgQWBBTopSzVEFFIz8Y6w270BvrEDDBPUDAfBgNV
HSMEGDAWgBTopSzVEFFIz8Y6w270BvrEDDBPUDAPBgNVHRMBAf8EBTADAQH/MA0G
CSqGSIb3DQEBCwUAA4ICAQCAD17WmP/yOv5I0QUXYgEYiJDVZvmDvOewWhKiTZDI
7hC6edDd4lx/hLmxzSOPHSj4K0wEA+0cVVArYCDp/uiWcV96c1531DdaYu/r2snd
FtUa8YhLB1jvBfxuTqJ1Q9+235PXDrOMprf4g7UMUk00M07D10ujIUorv0dccs3i
hmA+N83nHt9pGE2A2Cnwr++vmsy4jo9kqx5oXjAUovEP1xlOzP+tV6XjLy2tS4l1
rqfF48nnPzhK1nPUR/S7voHcvCfEV+LOCUp/PAZg0SbQDPTUBo0vajOtU4ChB84n
L5c/T2/NOHMR8kV+2d+b4rvoYaHaF9nFd0pC5d+vjAgn1BJRXXGP2tCSjxsMkwVO
C7KF8S1gXN+nXYCQbcrcRsAdCscSI+MJNv9IyMfxeZ/CtjBOQz4AYibrykp+EYL7
o0T9IW/1fjgBhC3qP/YXHLzkzUxdkktOsNdx7RzZNc0XACPcusnXx1Bw+YhQQFJT
sak7Fc8f0+4lFrQ6I2oVJ9CHWNDhSzxpXfY+JExOk8fytpvoFi4PyHyhWZOZOBSr
sshzq+cLKvLqR0rmUdrcC6PtXhM9got8xa/7cW5sbo393oZ720YEYhB4InpbmtDz
IawnZiugprouq6eaQ40KRv4xAJJXyX/yOHA0iGpjvqo8DLg5jzC8kIjulSUEIrgw
4w==
-----END CERTIFICATE-----
`)

func routerCaBundlePemBytes() ([]byte, error) {
	return _routerCaBundlePem, nil
}

func routerCaBundlePem() (*asset, error) {
	bytes, err := routerCaBundlePemBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/ca-bundle.pem", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCorednsPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  labels:
    name: test-coredns
  name: test-coredns
spec:
  securityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    command:
    - coredns
    image: replaced-at-runtime
    imagePullPolicy: IfNotPresent
    name: coredns
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: test-coredns-cm
    name: config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-coredns-cm
data:
  Corefile: |
    .:53 {
        bufsize 512
        errors
        log . {
            class error
        }
        health {
            lameduck 20s
        }
        ready
        template ANY MX {
            rcode NXDOMAIN
        }
        hosts {
            192.168.11.241     www.myocp-test.com
            2000::abcd     myocp-testv6.com
        }
        prometheus 127.0.0.1:9153
        forward . 8.8.8.8 {
            policy random
        }
        cache 900 {
            denial 9984 30
        }
        reload
    }
`)

func routerCorednsPodYamlBytes() ([]byte, error) {
	return _routerCorednsPodYaml, nil
}

func routerCorednsPodYaml() (*asset, error) {
	bytes, err := routerCorednsPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/coreDNS-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerEgressfirewallMultidomainYaml = []byte(`kind: EgressFirewall
apiVersion: k8s.ovn.org/v1
metadata:
  name: default
spec:
  egress:
  - type: Allow
    to:
      dnsName: registry-1.docker.io
  - type: Allow
    to:
      dnsName: www.facebook.com
    ports:
      - protocol: TCP
        port: 443
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
  - type: Deny
    to:
      cidrSelector: ::/0
`)

func routerEgressfirewallMultidomainYamlBytes() ([]byte, error) {
	return _routerEgressfirewallMultidomainYaml, nil
}

func routerEgressfirewallMultidomainYaml() (*asset, error) {
	bytes, err := routerEgressfirewallMultidomainYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/egressfirewall-multiDomain.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerEgressfirewallWildcardYaml = []byte(`kind: EgressFirewall
apiVersion: k8s.ovn.org/v1
metadata:
  name: default
spec:
  egress:
  - type: Allow
    to:
      dnsName: "*.google.com"
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
  - type: Deny
    to:
      cidrSelector: ::/0
`)

func routerEgressfirewallWildcardYamlBytes() ([]byte, error) {
	return _routerEgressfirewallWildcardYaml, nil
}

func routerEgressfirewallWildcardYaml() (*asset, error) {
	bytes, err := routerEgressfirewallWildcardYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/egressfirewall-wildcard.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerTestClientPodYaml = []byte(`apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-pod
  name: hello-pod
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
    name: hello-pod
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    ports:
    - containerPort: 8080
    - containerPort: 8443
`)

func routerTestClientPodYamlBytes() ([]byte, error) {
	return _routerTestClientPodYaml, nil
}

func routerTestClientPodYaml() (*asset, error) {
	bytes, err := routerTestClientPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/test-client-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerTestpod60350Yaml = []byte(`apiVersion: v1
kind: Pod 
metadata:
  name: testpod-60350
  labels:
    app: testpod-60350
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: testpod-60350
    image: quay.io/openshifttest/busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  dnsPolicy: ClusterFirst
  dnsConfig:
     searches: [8th.com, 9th.com, 10th.com, 11th.com, 12th.com, 13th.com, 14th.com, 15th.com, 16th.com, 17th.com, 18th.com, 19th.com, 20th.com, 21th.com, 22th.com, 23th.com, 24th.com, 25th.com, 26th.com, 27th.com, 28th.com, 29th.com, 30th.com, 31th.com, 32th.com]
`)

func routerTestpod60350YamlBytes() ([]byte, error) {
	return _routerTestpod60350Yaml, nil
}

func routerTestpod60350Yaml() (*asset, error) {
	bytes, err := routerTestpod60350YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/testpod-60350.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerTestpod60492Yaml = []byte(`apiVersion: v1
kind: Pod 
metadata:
  name: testpod-60492
  labels:
    app: testpod-60492
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: testpod-60492
    image: quay.io/openshifttest/busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  dnsPolicy: ClusterFirst
  dnsConfig:
     searches: [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd]

`)

func routerTestpod60492YamlBytes() ([]byte, error) {
	return _routerTestpod60492Yaml, nil
}

func routerTestpod60492Yaml() (*asset, error) {
	bytes, err := routerTestpod60492YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/testpod-60492.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerWebServerV4v6rcYaml = []byte(`apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: web-server-v4v6rc
    name: web-server-v4v6rc
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: web-server-v4v6rc
      spec:
        automountServiceAccountToken: false
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - image: quay.io/openshifttest/nginx-alpine@sha256:cee6930776b92dc1e93b73f9e5965925d49cff3d2e91e1d071c2f0ff72cbca29
          name: nginx
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-securev4v6
    name: service-securev4v6
  spec:
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: https
      port: 27443
      protocol: TCP
      targetPort: 8443
    selector:
      name: web-server-v4v6rc
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-unsecurev4v6
    name: service-unsecurev4v6
  spec:
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: web-server-v4v6rc
`)

func routerWebServerV4v6rcYamlBytes() ([]byte, error) {
	return _routerWebServerV4v6rcYaml, nil
}

func routerWebServerV4v6rcYaml() (*asset, error) {
	bytes, err := routerWebServerV4v6rcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router/web-server-v4v6rc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"router/ca-bundle.pem":                   routerCaBundlePem,
	"router/coreDNS-pod.yaml":                routerCorednsPodYaml,
	"router/egressfirewall-multiDomain.yaml": routerEgressfirewallMultidomainYaml,
	"router/egressfirewall-wildcard.yaml":    routerEgressfirewallWildcardYaml,
	"router/test-client-pod.yaml":            routerTestClientPodYaml,
	"router/testpod-60350.yaml":              routerTestpod60350Yaml,
	"router/testpod-60492.yaml":              routerTestpod60492Yaml,
	"router/web-server-v4v6rc.yaml":          routerWebServerV4v6rcYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"router": {nil, map[string]*bintree{
		"ca-bundle.pem":                   {routerCaBundlePem, map[string]*bintree{}},
		"coreDNS-pod.yaml":                {routerCorednsPodYaml, map[string]*bintree{}},
		"egressfirewall-multiDomain.yaml": {routerEgressfirewallMultidomainYaml, map[string]*bintree{}},
		"egressfirewall-wildcard.yaml":    {routerEgressfirewallWildcardYaml, map[string]*bintree{}},
		"test-client-pod.yaml":            {routerTestClientPodYaml, map[string]*bintree{}},
		"testpod-60350.yaml":              {routerTestpod60350Yaml, map[string]*bintree{}},
		"testpod-60492.yaml":              {routerTestpod60492Yaml, map[string]*bintree{}},
		"web-server-v4v6rc.yaml":          {routerWebServerV4v6rcYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
